# Generated by Django 5.1.7 on 2025-03-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('Apple', 'APPLE'), ('Samsung', 'Samsung'), ('Huawei', 'Huawei'), ('Xiaomi', 'Xiaomi'), ('Oppo', 'Oppo'), ('Vivo', 'Vivo'), ('Realme', 'Realme'), ('Oneplus', 'Oneplus'), ('Google', 'Google'), ('Nokia', 'Nokia'), ('Sony', 'Sony'), ('LG', 'LG'), ('HTC', 'HTC'), ('Motorola', 'Motorola'), ('Lenovo', 'Lenovo'), ('Asus', 'Asus'), ('ZTE', 'ZTE'), ('Alcatel', 'Alcatel'), ('Tecno', 'Tecno'), ('Infinix', 'Infinix'), ('Itel', 'Itel'), ('Gionee', 'Gionee')], max_length=15, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description', models.TextField()),
                ('colour', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('battery', models.CharField(max_length=100)),
                ('camera', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('display', models.CharField(max_length=100)),
                ('sim', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('features', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
